#!/bin/bash

mydir=`dirname $0`
if [[ $mydir = . ]]; then
  mydir=`pwd`
fi
dest=$HOME

#mkdir -p $HOME/bin/
excludes="install README"
for script in `ls $mydir`
do
  if [[ $excludes =~ $script ]]; then
    continue
  fi
  #ln -s $mydir/$script $HOME/bin/$script
  echo $mydir/$script $HOME/bin/$script
done;

echo "Installed to" $HOME/bin/
