#!/bin/bash

SERVERS=/var/www/servers

function usage() {
  echo "Usage: `basename $0` options (-a /path/to/maintenance-site) (-r) (-s vhost) -h for help";
  exit $E_OPTERROR;
}

if ( ! getopts "a:rs:h" opt); then
  usage
fi

while getopts "a:rs:" opt; do
  case "$opt" in
    "a")
      #echo "Option -$opt is specified: $OPTARG"
      ADD=true
      MAINTSITE=$OPTARG
      ;;
    "r")
      #echo "Option -$opt is specified: $OPTARG"
      ADD=false
      ;;
    "s")
      #echo "Option -$opt is specified: $OPTARG"
      VHOST=$OPTARG
      ;;
    ":")
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
    "?")
      echo "Unknown option $OPTARG." >&2
      exit 1
      ;;
    *)
      # Should not occur
      echo "Unknown error while processing options." >&2
      exit 1
      ;;
  esac
done

if $ADD
then
  echo "Enabling maintenance mode for $VHOST..."
  ln -s $MAINTSITE $SERVERS/$VHOST/down.html
else
  echo "Disabling maintenance mode for $VHOST..."
  rm -v $SERVERS/$VHOST/down.html
fi
